name: agropro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  flutter_screenutil: ^5.9.1
  gap: ^3.0.1
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  firebase_core: ^2.31.0
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1
  flutter_shimmer: ^2.1.2
  oktoast: ^3.4.0
  google_fonts: ^6.2.1
  camera: ^0.11.0

  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  rolling_bottom_bar: ^0.2.2
  intl_phone_number_input: ^0.7.4
  iconsax: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
    - assets/images/

 