// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9usfqNYsg7OOZjIfANMGwc8z_xGJIIs8',
    appId: '1:811294422460:web:8ec406963bc830133b67b9',
    messagingSenderId: '811294422460',
    projectId: 'agricpro-connect',
    authDomain: 'agricpro-connect.firebaseapp.com',
    databaseURL: 'https://agricpro-connect-default-rtdb.firebaseio.com',
    storageBucket: 'agricpro-connect.appspot.com',
    measurementId: 'G-20E07RK69E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1cXoLhg4itFFv9kh334HjKy2JT0VUsMw',
    appId: '1:811294422460:android:58b3abf0584052183b67b9',
    messagingSenderId: '811294422460',
    projectId: 'agricpro-connect',
    databaseURL: 'https://agricpro-connect-default-rtdb.firebaseio.com',
    storageBucket: 'agricpro-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApc3-QEwk3Dk9oKKgeVnqs24H7zgAmqJc',
    appId: '1:811294422460:ios:f92cbefaff6ba6c83b67b9',
    messagingSenderId: '811294422460',
    projectId: 'agricpro-connect',
    databaseURL: 'https://agricpro-connect-default-rtdb.firebaseio.com',
    storageBucket: 'agricpro-connect.appspot.com',
    iosBundleId: 'com.example.agropro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApc3-QEwk3Dk9oKKgeVnqs24H7zgAmqJc',
    appId: '1:811294422460:ios:f92cbefaff6ba6c83b67b9',
    messagingSenderId: '811294422460',
    projectId: 'agricpro-connect',
    databaseURL: 'https://agricpro-connect-default-rtdb.firebaseio.com',
    storageBucket: 'agricpro-connect.appspot.com',
    iosBundleId: 'com.example.agropro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9usfqNYsg7OOZjIfANMGwc8z_xGJIIs8',
    appId: '1:811294422460:web:977792f0ea9a6c313b67b9',
    messagingSenderId: '811294422460',
    projectId: 'agricpro-connect',
    authDomain: 'agricpro-connect.firebaseapp.com',
    databaseURL: 'https://agricpro-connect-default-rtdb.firebaseio.com',
    storageBucket: 'agricpro-connect.appspot.com',
    measurementId: 'G-6CVYGJWRQ9',
  );

}