// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDmj3GG9xtHiyIk6VyRt16php4tIO8IU',
    appId: '1:631335126066:web:f02c47f026c0769700e82b',
    messagingSenderId: '631335126066',
    projectId: 'macwin-6956b',
    authDomain: 'macwin-6956b.firebaseapp.com',
    storageBucket: 'macwin-6956b.appspot.com',
    measurementId: 'G-7NNMCQW11P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvjq22v8EY0gwnBsVsaVtw7cNX3Dl9lE',
    appId: '1:631335126066:android:eef5f96a4dbb040700e82b',
    messagingSenderId: '631335126066',
    projectId: 'macwin-6956b',
    storageBucket: 'macwin-6956b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgv4oLc9FSdzkPxdOiYNAFon-712sjXc',
    appId: '1:631335126066:ios:03142103a1945c0400e82b',
    messagingSenderId: '631335126066',
    projectId: 'macwin-6956b',
    storageBucket: 'macwin-6956b.appspot.com',
    androidClientId: '631335126066-cq1hh83sr1mlbh6p1q65pnmdjk1sj76o.apps.googleusercontent.com',
    iosClientId: '631335126066-5pi1i8830polc23b9rm7e95o35olg5f3.apps.googleusercontent.com',
    iosBundleId: 'com.app.macwin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgv4oLc9FSdzkPxdOiYNAFon-712sjXc',
    appId: '1:631335126066:ios:50c7e4f56d2f61fe00e82b',
    messagingSenderId: '631335126066',
    projectId: 'macwin-6956b',
    storageBucket: 'macwin-6956b.appspot.com',
    androidClientId: '631335126066-cq1hh83sr1mlbh6p1q65pnmdjk1sj76o.apps.googleusercontent.com',
    iosClientId: '631335126066-3rmipeum0vgm117msgp17g5o36ecvs93.apps.googleusercontent.com',
    iosBundleId: 'com.app.macwin.RunnerTests',
  );
}
